export interface VibeDefinition {
  id: string;
  name: string;
  tagline: string;
  icon: string;
  colors: {
    background: string;
    foreground: string;
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    accent: string;
    accentForeground: string;
    muted: string;
    mutedForeground: string;
    card: string;
    cardForeground: string;
    border: string;
    ring: string;
  };
  fontFamily: string;
  googleFont?: string;
  animationClass: string;
  backgroundEffect?: string;
  glowColor?: string;
  soundTrack: string;
}

export const VIBES: VibeDefinition[] = [
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    tagline: "Neon-glitch dystopia",
    icon: "⚡",
    colors: {
      background: "#0a0a0f",
      foreground: "#e0e0ff",
      primary: "#00f0ff",
      primaryForeground: "#000000",
      secondary: "#1a1a2e",
      secondaryForeground: "#00f0ff",
      accent: "#ff00aa",
      accentForeground: "#ffffff",
      muted: "#16162a",
      mutedForeground: "#7878a0",
      card: "#0f0f1e",
      cardForeground: "#e0e0ff",
      border: "#2a2a4a",
      ring: "#00f0ff",
    },
    fontFamily: "'Share Tech Mono', monospace",
    googleFont: "Share+Tech+Mono",
    animationClass: "vibe-cyberpunk",
    backgroundEffect: "cyber-grid",
    glowColor: "#00f0ff",
    soundTrack: "synth",
  },
  {
    id: "zen",
    name: "Zen",
    tagline: "Wabi-sabi serenity",
    icon: "🍃",
    colors: {
      background: "#1a1814",
      foreground: "#d4c5a9",
      primary: "#8b7355",
      primaryForeground: "#1a1814",
      secondary: "#2a2620",
      secondaryForeground: "#d4c5a9",
      accent: "#6b8f71",
      accentForeground: "#1a1814",
      muted: "#252218",
      mutedForeground: "#8a7e6b",
      card: "#1f1d18",
      cardForeground: "#d4c5a9",
      border: "#3a352a",
      ring: "#8b7355",
    },
    fontFamily: "'Noto Serif', serif",
    googleFont: "Noto+Serif",
    animationClass: "vibe-zen",
    soundTrack: "lofi",
  },
  {
    id: "brutalist",
    name: "Brutalist",
    tagline: "Raw concrete power",
    icon: "🏗️",
    colors: {
      background: "#1a1a1a",
      foreground: "#ffffff",
      primary: "#ffffff",
      primaryForeground: "#000000",
      secondary: "#333333",
      secondaryForeground: "#ffffff",
      accent: "#ff3300",
      accentForeground: "#ffffff",
      muted: "#2a2a2a",
      mutedForeground: "#888888",
      card: "#222222",
      cardForeground: "#ffffff",
      border: "#444444",
      ring: "#ffffff",
    },
    fontFamily: "'Space Mono', monospace",
    googleFont: "Space+Mono",
    animationClass: "vibe-brutalist",
    soundTrack: "ambient",
  },
  {
    id: "retro-crt",
    name: "Retro CRT",
    tagline: "Phosphor scanlines",
    icon: "📺",
    colors: {
      background: "#0a0a0a",
      foreground: "#33ff33",
      primary: "#33ff33",
      primaryForeground: "#000000",
      secondary: "#0d1a0d",
      secondaryForeground: "#33ff33",
      accent: "#66ff66",
      accentForeground: "#000000",
      muted: "#111a11",
      mutedForeground: "#228822",
      card: "#0d0d0d",
      cardForeground: "#33ff33",
      border: "#1a331a",
      ring: "#33ff33",
    },
    fontFamily: "'VT323', monospace",
    googleFont: "VT323",
    animationClass: "vibe-crt",
    backgroundEffect: "scanlines",
    glowColor: "#33ff33",
    soundTrack: "ambient",
  },
  {
    id: "luxury",
    name: "Luxury",
    tagline: "Gold butter elegance",
    icon: "✨",
    colors: {
      background: "#0c0a06",
      foreground: "#f5e6c8",
      primary: "#d4a843",
      primaryForeground: "#0c0a06",
      secondary: "#1c1810",
      secondaryForeground: "#d4a843",
      accent: "#e8c878",
      accentForeground: "#0c0a06",
      muted: "#1a1610",
      mutedForeground: "#8a7a5a",
      card: "#12100a",
      cardForeground: "#f5e6c8",
      border: "#2a2418",
      ring: "#d4a843",
    },
    fontFamily: "'Playfair Display', serif",
    googleFont: "Playfair+Display",
    animationClass: "vibe-luxury",
    glowColor: "#d4a843",
    soundTrack: "lofi",
  },
  {
    id: "hacker",
    name: "Hacker",
    tagline: "Matrix rain terminal",
    icon: "💀",
    colors: {
      background: "#000000",
      foreground: "#00ff41",
      primary: "#00ff41",
      primaryForeground: "#000000",
      secondary: "#001100",
      secondaryForeground: "#00ff41",
      accent: "#008f11",
      accentForeground: "#00ff41",
      muted: "#0a0a0a",
      mutedForeground: "#006622",
      card: "#050505",
      cardForeground: "#00ff41",
      border: "#003300",
      ring: "#00ff41",
    },
    fontFamily: "'Fira Code', monospace",
    googleFont: "Fira+Code",
    animationClass: "vibe-hacker",
    backgroundEffect: "matrix-rain",
    glowColor: "#00ff41",
    soundTrack: "synth",
  },
  {
    id: "kawaii",
    name: "Kawaii",
    tagline: "Pastel dream world",
    icon: "🌸",
    colors: {
      background: "#1a1520",
      foreground: "#ffd4e8",
      primary: "#ff8ec8",
      primaryForeground: "#1a1520",
      secondary: "#2a2030",
      secondaryForeground: "#ffb8d8",
      accent: "#c490ff",
      accentForeground: "#1a1520",
      muted: "#221a28",
      mutedForeground: "#a888b8",
      card: "#1e1825",
      cardForeground: "#ffd4e8",
      border: "#3a2848",
      ring: "#ff8ec8",
    },
    fontFamily: "'Quicksand', sans-serif",
    googleFont: "Quicksand",
    animationClass: "vibe-kawaii",
    glowColor: "#ff8ec8",
    soundTrack: "lofi",
  },
  {
    id: "dark-void",
    name: "Dark Void",
    tagline: "Abyss gazes back",
    icon: "🕳️",
    colors: {
      background: "#050508",
      foreground: "#c8c8e0",
      primary: "#8855ff",
      primaryForeground: "#ffffff",
      secondary: "#101018",
      secondaryForeground: "#a0a0c0",
      accent: "#6633cc",
      accentForeground: "#ffffff",
      muted: "#0a0a12",
      mutedForeground: "#5a5a78",
      card: "#08080e",
      cardForeground: "#c8c8e0",
      border: "#1a1a28",
      ring: "#8855ff",
    },
    fontFamily: "'Inter', sans-serif",
    googleFont: "Inter",
    animationClass: "vibe-void",
    backgroundEffect: "void-particles",
    glowColor: "#8855ff",
    soundTrack: "ambient",
  },
  {
    id: "synthwave",
    name: "Synthwave",
    tagline: "Vapor retro-future",
    icon: "🌅",
    colors: {
      background: "#0f0728",
      foreground: "#f0d0ff",
      primary: "#ff6ec7",
      primaryForeground: "#0f0728",
      secondary: "#1a0e38",
      secondaryForeground: "#ff6ec7",
      accent: "#7b68ee",
      accentForeground: "#ffffff",
      muted: "#150a32",
      mutedForeground: "#8866aa",
      card: "#120930",
      cardForeground: "#f0d0ff",
      border: "#2a1858",
      ring: "#ff6ec7",
    },
    fontFamily: "'Orbitron', sans-serif",
    googleFont: "Orbitron",
    animationClass: "vibe-synthwave",
    backgroundEffect: "synth-grid",
    glowColor: "#ff6ec7",
    soundTrack: "synth",
  },
  {
    id: "glassmorphism",
    name: "Glassmorphism",
    tagline: "Frosted crystal UI",
    icon: "❄️",
    colors: {
      background: "#0a0e1a",
      foreground: "#e0e8ff",
      primary: "#60a5fa",
      primaryForeground: "#0a0e1a",
      secondary: "#141e30",
      secondaryForeground: "#a0b8e0",
      accent: "#38bdf8",
      accentForeground: "#0a0e1a",
      muted: "#101828",
      mutedForeground: "#6888a8",
      card: "#0e1424",
      cardForeground: "#e0e8ff",
      border: "rgba(96, 165, 250, 0.15)",
      ring: "#60a5fa",
    },
    fontFamily: "'Inter', sans-serif",
    googleFont: "Inter",
    animationClass: "vibe-glass",
    backgroundEffect: "glass-orbs",
    glowColor: "#60a5fa",
    soundTrack: "ambient",
  },
];

export function getVibeById(id: string): VibeDefinition {
  return VIBES.find((v) => v.id === id) ?? VIBES[0];
}
