import { Router, Request, Response } from 'express';
import { execFile } from 'child_process';
import path from 'path';

const router = Router();

/**
 * POST /api/grafset/agent
 *
 * Accepts a short creative seed and returns a structured prompt
 * generated by the Python creative-prompt builder (app.py).
 */
router.post('/agent', (req: Request, res: Response) => {
  const { seed, medium } = req.body || {};

  if (!seed || typeof seed !== 'string' || !seed.trim()) {
    return res.status(400).json({ error: 'A seed phrase is required' });
  }

  const sanitizedSeed = seed.trim().slice(0, 500);

  const appPath = path.resolve(__dirname, '..', '..', '..', 'app.py');
  const args = ['--prompt'];

  if (
    medium &&
    typeof medium === 'string' &&
    ['photo', 'video', 'music', 'art', 'poem'].includes(medium)
  ) {
    args.push('--medium', medium);
  }
  args.push(sanitizedSeed);

  execFile('python3', [appPath, ...args], { timeout: 10_000 }, (err, stdout, stderr) => {
    if (err) {
      console.error('Agent error:', stderr || err.message);
      return res.status(500).json({ error: 'Agent could not process the request' });
    }

    res.json({ prompt: stdout.trim(), seed: sanitizedSeed });
  });
});

/**
 * GET /api/grafset/ideas
 *
 * Returns the catalog of smart cheap ideas with agent tips.
 */
router.get('/ideas', (_req: Request, res: Response) => {
  const ideas = [
    {
      id: 'gi-001',
      title: 'Quick-turnaround social banners',
      category: 'design',
      estimatedCost: 'Free – $5',
      medium: 'art',
      agentTip: 'Use the art prompt builder with bold triadic colors and minimal text overlay.',
    },
    {
      id: 'gi-002',
      title: 'Micro-video product teasers',
      category: 'marketing',
      estimatedCost: 'Free – $10',
      medium: 'video',
      agentTip: 'Start with a dolly-in reveal, add subtitle hooks at 3s and 8s, close with CTA.',
    },
    {
      id: 'gi-003',
      title: 'AI-powered blog outlines',
      category: 'content',
      estimatedCost: 'Free',
      medium: 'art',
      agentTip: 'Provide one sentence and the agent returns a 5-section outline with hooks.',
    },
    {
      id: 'gi-004',
      title: 'Brand voice poem cards',
      category: 'branding',
      estimatedCost: 'Free – $2',
      medium: 'poem',
      agentTip: 'Use the poem prompt builder with haiku form and one sensory image per line.',
    },
    {
      id: 'gi-005',
      title: 'Soundtrack loops for ads',
      category: 'marketing',
      estimatedCost: 'Free – $15',
      medium: 'music',
      agentTip: 'Specify BPM, genre feel, and a single lead instrument for structure and loops.',
    },
    {
      id: 'gi-006',
      title: 'Community engagement templates',
      category: 'social',
      estimatedCost: 'Free',
      medium: 'art',
      agentTip: 'The agent tailors each template to your niche and adds engagement hooks.',
    },
  ];

  res.json({ ideas });
});

export default router;
