"""
Builds interim and final Markdown reports from MemoryStore findings.
"""
from __future__ import annotations

import os
import time
from collections import defaultdict
from typing import Any

from agents.memory_store import Finding, MemoryStore


def _now_str() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())


def _elapsed_str(start: float) -> str:
    secs = int(time.time() - start)
    h, rem = divmod(secs, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}h {m:02d}m {s:02d}s"


def _rank_findings(findings: list[Finding], top_n: int = 15) -> list[Finding]:
    """Deduplicate by opportunity text, rank by speed_to_money desc."""
    seen: set[str] = set()
    unique: list[Finding] = []
    for f in findings:
        key = f.opportunity.lower().strip()
        if key not in seen:
            seen.add(key)
            unique.append(f)
    unique.sort(key=lambda f: f.speed_to_money, reverse=True)
    return unique[:top_n]


def build_interim_report(
    store: MemoryStore,
    start_time: float,
    checkpoint_label: str,
) -> str:
    findings = store.get_findings()
    statuses = store.get_statuses()
    elapsed = _elapsed_str(start_time)

    lines: list[str] = [
        f"# Interim Report — Checkpoint {checkpoint_label}",
        f"**Generated:** {_now_str()}  |  **Elapsed:** {elapsed}",
        "",
        "## Agent Status",
        "",
        "| Agent | Status | Cycles | Topics |",
        "|-------|--------|--------|--------|",
    ]
    for aid, s in sorted(statuses.items()):
        lines.append(f"| {aid} | {s.status} | {s.cycles_completed} | {', '.join(s.topics_covered)} |")

    lines += [
        "",
        f"## Findings so far: {len(findings)} total",
        "",
        "### Top opportunities (speed-to-money)",
        "",
    ]
    top = _rank_findings(findings, top_n=10)
    for i, f in enumerate(top, 1):
        lines.append(
            f"**{i}. {f.opportunity}**  \n"
            f"Topic: `{f.topic}` | Speed: {f.speed_to_money}/10 | Effort: {f.effort}  \n"
            f"First action: {f.first_action}  \n"
            f"Potential: {f.earning_potential}  \n"
        )

    return "\n".join(lines)


def build_final_report(store: MemoryStore, start_time: float) -> str:
    findings = store.get_findings()
    statuses = store.get_statuses()
    elapsed = _elapsed_str(start_time)

    top15 = _rank_findings(findings, top_n=15)

    # Rough total estimate (sum of lower bound of ranges)
    total_low = 0
    for f in top15:
        pot = f.earning_potential
        import re
        nums = re.findall(r"\d[\d,]*", pot.replace(",", ""))
        if nums:
            total_low += int(nums[0])

    lines: list[str] = [
        "# FINAL REPORT — 11-Hour Multi-Agent Research Session",
        f"**Generated:** {_now_str()}  |  **Total runtime:** {elapsed}",
        "",
        "---",
        "",
        "## Top 15 Opportunities — Ranked by Speed-to-Money",
        "",
    ]

    for rank, f in enumerate(top15, 1):
        lines.append(
            f"### #{rank} — {f.opportunity}\n"
            f"- **Topic:** {f.topic}\n"
            f"- **Speed-to-money:** {f.speed_to_money}/10\n"
            f"- **Effort:** {f.effort}\n"
            f"- **Earning potential:** {f.earning_potential}\n"
            f"- **Exact next action:** {f.first_action}\n"
            f"- **Discovered by:** {f.agent_id} (cycle {f.cycle})\n"
        )

    lines += [
        "---",
        "",
        f"## Total Estimated Earning Potential (conservative, top 15 combined)",
        f"**≥ ${total_low:,} / month** across all opportunities",
        "",
        "---",
        "",
        "## Agent Summary",
        "",
        "| Agent | Status | Cycles | Topics Covered |",
        "|-------|--------|--------|----------------|",
    ]
    for aid, s in sorted(statuses.items()):
        lines.append(f"| {aid} | {s.status} | {s.cycles_completed} | {', '.join(s.topics_covered)} |")

    lines += [
        "",
        f"**Total findings collected:** {len(findings)}",
        "",
        "---",
        "*Report auto-generated by the 11-hour multi-agent orchestrator.*",
    ]

    return "\n".join(lines)


def save_report(content: str, path: str) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as fh:
        fh.write(content)
