"""Input binding for the KUTT24 Value Engine.

Raw input arrives in many shapes: a plain string from the operator, a task id
pulled from the task bank, or a follow-up generated by a previous judgement.
The InputBinder normalizes all of these into the single ``Input`` contract that
the rest of the pipeline understands.

There is deliberately *no* dependency on any social platform here. KUTT24 does
not ingest X/Twitter; inputs are operator-driven or task-bank-driven only.
"""

from __future__ import annotations

from typing import Optional

from .contracts import Input, Judgement, Verdict
from .task_bank import TaskBank


class InputBinder:
    def __init__(self, task_bank: Optional[TaskBank] = None) -> None:
        self.task_bank = task_bank or TaskBank()

    def from_text(self, text: str, source: str = "operator") -> Input:
        text = (text or "").strip()
        if not text:
            raise ValueError("Empty input is not allowed; the engine is memory-first, not noise-first.")
        return Input(text=text, source=source)

    def from_task(self, task_id: str) -> Input:
        task = self.task_bank.get(task_id)
        return Input(
            text=task.prompt,
            task_id=task.id,
            source="task_bank",
            meta={"category": task.category, "acceptance": task.acceptance},
        )

    def follow_up(self, prev_input: Input, judgement: Judgement) -> Optional[Input]:
        """Derive the next input from a judgement.

        PASS  -> no follow-up (work is done for this input).
        REWORK-> re-enter the same objective with the rework notes attached.
        BLOCK -> no follow-up; the loop must surface the block to an operator.
        """

        if judgement.verdict is Verdict.PASS:
            return None
        if judgement.verdict is Verdict.BLOCK:
            return None

        notes = "; ".join(judgement.rework_notes) or "address the judge's reasons"
        return Input(
            text=prev_input.text,
            task_id=prev_input.task_id,
            source="rework",
            meta={**prev_input.meta, "rework_notes": judgement.rework_notes, "rework_of": prev_input.id, "guidance": notes},
        )
